import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { AuthProvider } from '@/context/AuthContext';
import Navbar from '@/components/Navbar'; // <-- ایمپورت کردن نوبار

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'TodoApp',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Navbar /> {/* <-- اضافه کردن نوبار به اینجا */}
          <main>{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}